import os
from pathlib import Path


def define_env(env):
    @env.macro
    def api_link(text, module_path):
        """
        Macro generated by Claude to allow different handling of api links depending on whether api-autonav is enabled
        The goal is to allow us to run without api-autonav in CI, since api-autonav is very slow, while still using it on deployment.

        Return a cross-reference link to API docs, or plain text when api-autonav is disabled.

        When ENABLE_API_AUTONAV is set, returns ``[text][module_path]`` so that
        mkdocs-autorefs resolves the link normally.  Otherwise, validates that
        the corresponding source file (or package) exists and returns the text
        without a link so the build can proceed in strict mode.
        """
        parts = module_path.split(".")
        # Try as a module file first, then as a package directory
        file_path = Path(*parts).with_suffix(".py")
        package_path = Path(*parts) / "__init__.py"
        # For function-level refs like mod.func, check the module part
        parent_file = Path(*parts[:-1]).with_suffix(".py") if len(parts) > 1 else None

        if not (
            file_path.exists()
            or package_path.exists()
            or (parent_file and parent_file.exists())
        ):
            raise FileNotFoundError(
                f"api_link: module path '{module_path}' does not correspond to "
                f"any existing file (checked {file_path}, {package_path}"
                + (f", {parent_file})" if parent_file else ")")
            )

        if os.environ.get("ENABLE_API_AUTONAV"):
            return f"[{text}][{module_path}]"
        return text

    @env.macro
    def include_file(path):
        """Include the contents of an external file, raising an error if it does not exist.

        Parameters
        ----------
        path : str
            Path to the file to include, relative to the project root.
        """
        file_path = Path(path)
        if not file_path.is_file():
            raise FileNotFoundError(f"include_file: '{path}' does not exist")
        return file_path.read_text()

    @env.macro
    def plotly_embed(src, id, height="775px", caption=""):
        """
        This is a macro function added by Claude to allow the embedding of plotly plots which can be expanded to full screen.

        Embed a Plotly HTML file with a fullscreen button.

        Parameters
        ----------
        src : str
            Path to the Plotly HTML file, relative to the project root
            (e.g. "docs/_figs/my_plot.html").
        id : str
            A unique HTML id for the iframe (must be unique per page).
        height : str
            CSS height of the embedded iframe, e.g. "750px" or "60vh".
        caption : str
            Optional caption rendered as a <figcaption> below the iframe.
            Supports inline HTML. When provided the whole embed is wrapped in
            a <figure> with width:100% so the iframe is never squished.
        """
        if not Path(src).is_file():
            raise FileNotFoundError(
                f"plotly_embed: '{src}' does not exist "
                f"(referenced from page '{env.page.file.src_uri}')"
            )

        # Convert project-root-relative path to a URL relative to the served page.
        # Files under docs/ are served from the site root, so strip the docs_dir prefix.
        docs_dir = Path(env.conf["docs_dir"])
        site_path = Path(src).resolve().relative_to(docs_dir.resolve())
        page_dir = Path(env.page.file.dest_uri).parent
        relative_url = os.path.relpath(site_path, page_dir)

        button = (
            f'<div style="display:flex; justify-content:flex-end; margin:.25rem 0;">\n'
            f"<button onclick=\"document.getElementById('{id}').requestFullscreen()\"\n"
            f'  style="cursor:pointer; background:none; border:1px solid #ccc; padding:4px 12px; border-radius:4px;">\n'
            f"  Fullscreen Plot &#x2922;\n"
            f"</button>\n"
            f"</div>\n"
        )
        iframe = (
            f"<iframe\n"
            f'  id="{id}"\n'
            f'  src="{relative_url}"\n'
            f'  style="width:100%; height:{height}; border:none;"\n'
            f"  allowfullscreen></iframe>"
        )
        if caption:
            return (
                f'<div style="width:100%; margin:0;">\n'
                f"{button}"
                f"{iframe}\n"
                f'<p style="width:100%; text-align:center; font-style:italic; margin-top:0.5em;">{caption}</p>\n'
                f"</div>"
            )
        return button + iframe
