"""
Asset Generator for applying the Latent Causal Variable method of O'Connor and Price  to a list of upstream and
downstream traits.  Each upstream trait is tested against each downstream trait.
"""

from typing import Mapping, Sequence

from attrs import frozen

from mecfs_bio.build_system.task.base_task import Task
from mecfs_bio.build_system.task.concat_frames_task import ConcatFramesTask
from mecfs_bio.build_system.task.harmonize_gwas_with_reference_table_via_chrom_pos_alleles import (
    HarmonizeGWASWithReferenceViaAlleles,
)
from mecfs_bio.build_system.task.lcv.lcv_task import LCVConfig, LCVTask
from mecfs_bio.build_system.task.pipe_dataframe_task import ParquetOutFormat
from mecfs_bio.build_system.task.pipes.composite_pipe import CompositePipe
from mecfs_bio.build_system.task.pipes.data_processing_pipe import DataProcessingPipe
from mecfs_bio.build_system.task.pipes.identity_pipe import IdentityPipe
from mecfs_bio.build_system.task.pipes.set_col_pipe import SetColToConstantPipe
from mecfs_bio.build_system.task.pipes.uniquepipe import UniquePipe
from mecfs_bio.constants.gwaslab_constants import (
    GWASLAB_CHROM_COL,
    GWASLAB_EFFECT_ALLELE_COL,
    GWASLAB_NON_EFFECT_ALLELE_COL,
    GWASLAB_POS_COL,
    GWASLAB_RSID_COL,
)

UPSTREAM_TRAIT_COL = "upstream_trait"
DOWNSTREAM_TRAIT_COL = "downstream_trait"

@frozen
class LCVRun:
    """
    The Tasks required to run LCV for a particular upstream-task/ downstream-task pair
    """

    harmonization_task: Task
    lcv_task: Task


@frozen
class LCVTaskGroup:
    """
    A group of tasks generated by the LCV asset generator
    """

    lcv_run_mapping: Mapping[tuple[str, str], LCVRun]
    agg_task: Task

    def terminal_tasks(self) -> list[Task]:
        return [self.agg_task]


@frozen
class LCVSourceTraitInfo:
    """
    Describes a trait being passed as input to the LCV asset generator
    """

    name: str
    df_task: Task
    pipe: DataProcessingPipe = IdentityPipe()


def lcv_generate(
    base_name: str,
    upstream_traits: Sequence[LCVSourceTraitInfo],
    downstream_traits: Sequence[LCVSourceTraitInfo],
    consolidated_ld_scores_task: Task,
    config: LCVConfig,
) -> LCVTaskGroup:
    """
    Apply LCV for every upstream-trait/downstream-trait pair
    """
    unique_pipe = UniquePipe(
        by=[
            GWASLAB_CHROM_COL,
            GWASLAB_POS_COL,
            GWASLAB_EFFECT_ALLELE_COL,
            GWASLAB_NON_EFFECT_ALLELE_COL,
        ],
        keep="first",
        order_by=[GWASLAB_RSID_COL],
    )
    run_mapping = {}
    task_list = []
    pre_agg_pipes = []
    for us in upstream_traits:
        for ds in downstream_traits:
            harmonization_task = HarmonizeGWASWithReferenceViaAlleles.create(
                asset_id=f"{base_name}_{us.name}_harmonize_with_{ds.name}_for_lcv",
                gwas_data_task=us.df_task,
                reference_task=ds.df_task,
                gwas_pipe=CompositePipe(
                    [
                        us.pipe,
                        unique_pipe,
                    ]
                ),
                ref_pipe=CompositePipe(
                    [
                        ds.pipe,
                        unique_pipe,
                    ]
                ),
                palindrome_strategy="drop",
            )

            lcv_task = LCVTask.create(
                base_name + "_lcv_" + us.name + "_" + ds.name,
                trait_1_data=harmonization_task,
                trait_2_data=ds.df_task,
                consolidated_ld_scores=consolidated_ld_scores_task,
                config=config,
                trait_2_pipe=CompositePipe(
                    [
                        ds.pipe,
                        unique_pipe,
                    ]
                ),
            )
            pre_agg_pipes.append(
                CompositePipe(
                    [
                        SetColToConstantPipe(
                            col_name=UPSTREAM_TRAIT_COL, constant=us.name
                        ),
                        SetColToConstantPipe(
                            col_name=DOWNSTREAM_TRAIT_COL, constant=ds.name
                        ),
                    ]
                )
            )
            run_mapping[(us.name, ds.name)] = LCVRun(
                lcv_task=lcv_task, harmonization_task=harmonization_task
            )
            task_list.append(lcv_task)
    agg_task = ConcatFramesTask.create(
        asset_id=base_name + "_lcv_agg",
        frames_tasks=task_list,
        out_format=ParquetOutFormat(),
        frames_pipes=pre_agg_pipes,
    )
    return LCVTaskGroup(lcv_run_mapping=run_mapping, agg_task=agg_task)
