from mecfs_bio.constants.curated_gene_set_collections.curated_mecfs_gene_sets import (
    CURATED_POTENTIAL_MECFS_GENE_SETS_ALL,
)

_REDUCED_GENE_SETS_NAMES = set(
    [
        "GOBP_AUTONOMIC_NERVOUS_SYSTEM_DEVELOPMENT",
        "GOBP_ADRENERGIC_RECEPTOR_SIGNALING_PATHWAY",
        "GOBP_SYNAPTIC_TRANSMISSION_CHOLINERGIC",
        "GOBP_ENDOTHELIAL_CELL_ACTIVATION",
        "BIOCARTA_NOS1_PATHWAY",
        "GOBP_ANTEROGRADE_AXONAL_TRANSPORT",
        "BIOCARTA_NGF_PATHWAY",
        "HP_SENSORY_AXONAL_NEUROPATHY",
        "HP_MITOCHONDRIAL_RESPIRATORY_CHAIN_DEFECTS",
        "KEGG_ARACHIDONIC_ACID_METABOLISM",
        "KEGG_CITRATE_CYCLE_TCA_CYCLE",
        "GOBP_MICROGLIAL_CELL_ACTIVATION_INVOLVED_IN_IMMUNE_RESPONSE",
        "KEGG_CIRCADIAN_RHYTHM_MAMMAL",
        "GOMF_NEUREXIN_FAMILY_PROTEIN_BINDING",
        "GOBP_RESPONSE_TO_VIRUS",
    ]
)

CURATED_POTENTIAL_MECFS_GENE_SETS_REDUCED = [
    item
    for item in CURATED_POTENTIAL_MECFS_GENE_SETS_ALL
    if item.standard_name in _REDUCED_GENE_SETS_NAMES
]
