from pathlib import PurePath

from attrs import field, frozen

from mecfs_bio.build_system.meta.asset_id import AssetId
from mecfs_bio.build_system.meta.base_meta import FileMeta
from mecfs_bio.build_system.meta.read_spec.dataframe_read_spec import (
    DataFrameTextFormat,
)
from mecfs_bio.build_system.meta.read_spec.read_spec import ReadSpec


@frozen
class GWASLabLeadVariantsMeta(FileMeta):
    """
    Metadata describing a file that lists the lead variants from a GWAS.
    Such files are generated by GWASLAB.
    see: https://cloufield.github.io/gwaslab/utility_get_lead_novel/
    """

    @property
    def asset_id(self) -> AssetId:
        return self.id

    trait: str
    project: str
    id: AssetId = field(converter=AssetId)
    sub_dir: PurePath = PurePath("analysis/lead_variants")

    def read_spec(self) -> ReadSpec | None:
        return ReadSpec(format=DataFrameTextFormat(separator=","))
