from typing import Literal

GWASLAB_CHROM_COL = "CHR"
GWASLAB_POS_COL = "POS"
GWASLAB_EFFECT_ALLELE_COL = "EA"
GWASLAB_NON_EFFECT_ALLELE_COL = "NEA"
GWASLAB_INFO_SCORE_COL = "INFO"
GWASLAB_ODDS_RATIO_COL = "OR"
GWASLAB_BETA_COL = "BETA"
GWASLAB_P_COL = "P"
GWASLAB_MLOG10P_COL = "MLOG10P"
GWASLAB_EFFECT_ALLELE_FREQ_COL = "EAF"
GWASLAB_SAMPLE_SIZE_COLUMN = "N"
GWASLAB_SE_COL = "SE"
GWASLAB_STATUS_COL = "STATUS"
GWASLAB_RSID_COL = "rsID"
GWASLAB_SNPID_COL = "SNPID"

GwaslabKnownFormat = Literal["gwaslab", "regenie", "gwascatalog"]

GWASLabVCFRefFile = Literal["1kg_eur_hg38"]

GWASLAB_EUR_1K_GENOMES_NAME_38: GWASLabVCFRefFile = "1kg_eur_hg38"
GWASLAB_HUMAN_GENOME_NAME_38 = "ucsc_genome_hg38"

GWASLAB_EUR_1K_GENOMES_NAME_19 = "1kg_eur_hg19"
GWASLAB_HUMAN_GENOME_NAME_19 = "ucsc_genome_hg19"
