name: system_test_harmonization
on:
  schedule:
    - cron: "0 4 * * 1"   #Run Monday at 4 UTC
  workflow_dispatch: {}

jobs:
  lead_variants:
    timeout-minutes: 600
    name: Run Harmonization
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6
      - name: Run harmonization integration test
        uses: ./.github/actions/run-system-test
        with:
          pytest-target: test_mecfs_bio/system/test_harmonize_drop_ambiguous.py
          free-disk-space: "false"
