name: system_test_decodeme
on:
  schedule:
    - cron: "15 11 * * *"   #Run at 11:15 am daily
  workflow_dispatch: {}

jobs:
  lead_variants:
    timeout-minutes: 600
    name: Compute Lead Variants
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6
      - name: Run lead variants integration test
        uses: ./.github/actions/run-system-test
        with:
          pytest-target: test_mecfs_bio/system/test_decode_me_initial_analysis.py
