name: system_test_polypwas
on:
  schedule:
    - cron: "0 6 * * 4"   #Run Thursday at 6 UTC
  workflow_dispatch: {}

jobs:
  polypwas_system_test:
    timeout-minutes: 600
    name: Run polypwas system test
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v7
      - name: Run polypwas system test
        uses: ./.github/actions/run-system-test
        with:
          pytest-target: test_mecfs_bio/system/test_polypwas.py
