name: system_test_genetic_corr_by_ct_ldsc
on:
  schedule:
    - cron: "0 4 * * 2"   # Run Tuesday at 4 UTC
  workflow_dispatch: {}

jobs:
  ct_ldsc:
    timeout-minutes: 600
    name: Run CT-LDSC genetic correlation
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - uses: mathio/gha-cleanup@v1
        with:
          remove-browsers: true
          verbose: true
      - uses: prefix-dev/setup-pixi@v0.9.5
        name: Setup Pixi Environment
        with:
          pixi-version: v0.67.2
          cache: true
      - name: Run CT-LDSC integration test
        run: pixi r python -m pytest -s test_mecfs_bio/system/test_genetic_corr_system.py
