name: system_test_mixer
on:
  schedule:
    - cron: "0 4 * * 4"   #Run Thursday at 4 UTC
  workflow_dispatch: {}

jobs:
  mixer_system_test:
    timeout-minutes: 600
    name: Run MiXeR system test
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6
      - uses: prefix-dev/setup-pixi@v0.9.5
        name: Setup Pixi Environment
        with:
          pixi-version: v0.67.2
          cache: true
      - name: Install R packages
        run: pixi r invoke install-r-packages
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      - name: Run mixer integration test
        run:  pixi r python -m pytest -s test_mecfs_bio/system/test_mixer.py  # run  test using mixer example data

