name: system_test_hba_magma_decode_me
on:
  schedule:
    - cron: "0 4 * * 0"   #Run Sunday at 4 UTC
  workflow_dispatch: {}

jobs:
  lead_variants:
    timeout-minutes: 600
    name: Run HBA-MAGMA
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6
      - name: Run HBA-MAGMA integration test
        uses: ./.github/actions/run-system-test
        with:
          pytest-target: test_mecfs_bio/system/test_decode_me_hba_magma.py
