name: system_test_genetic_corr_by_ct_ldsc
on:
  schedule:
    - cron: "0 4 * * 2"   # Run Tuesday at 4 UTC
  workflow_dispatch: {}

jobs:
  ct_ldsc:
    timeout-minutes: 600
    name: Run CT-LDSC genetic correlation
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6
      - name: Run CT-LDSC integration test
        uses: ./.github/actions/run-system-test
        with:
          pytest-target: test_mecfs_bio/system/test_genetic_corr_system.py
